### ISSUE TITLE
Style the form

### ISSUE THREAD

**Issue by AliNisarAhmed** [AliNisarAhmed/credit-card#11]

**Comment by aditya12gusain** [comment]
You want it to be styled with css?

**Comment by AliNisarAhmed** [comment]
The project uses [https://styled-components.com/](styled components) library, so you will have to use that. The wrapping and use of some JS inside css is the only difference, otherwise it is very similar to css/sass.

**Comment by aditya12gusain** [comment]
Ok no problem I will do it

**Comment by aditya12gusain** [comment]
Any theme you want me to refer to ?

**Comment by aditya12gusain** [comment]
![image](https://user-images.githubusercontent.com/59219284/95042115-7f284880-06f6-11eb-8f80-50dc0d2e1260.png)


Can you help me with this error?
I have no experience with typescript.

**Comment by AliNisarAhmed** [comment]
Any theme is fine, just set the background color to any dark color and choose hover and focus colors appropriately. We could also change the colors based on credit card company of the card number.

Regarding the error, I have no idea what that is, but try deleting `node_modules` folder and run `yarn` again.
